[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "cohere==5.13.3",
    "openai==1.57.0",
    "requests>=2.32.4",
    "spacy>=3.8.7",
    "textblob>=0.19.0",
]
